import { ImageResponse } from "next/og";

export const size = { width: 1200, height: 630 };
export const contentType = "image/png";

/* The zone's Open Graph image for /blog, generated by a metadata route. */
export default function Image() {
  return new ImageResponse(<div style={{ fontSize: 96, display: "flex" }}>blog</div>, size);
}
